"Hello".charAt(4);
"Hello".concat("", "world");
"Hello".startsWith("H");
"Hello".endsWith("o");
"Hello".includes("x");
"Hello".indexOf("l");
"Hello".lastIndexOf("l");
"Hello".match(/[A-Z]/g);
"Hello".padStart(6,"?");
"Hello".padEnd(6,"?");
"Hello".repeat(3);
"Hello".replace("llo", "y");
"Hello".search("e");
"Hello".slice(1,3);
"Hello".split("");
"Hello".substring(2,4);
"Hello".toLowerCase();
"Hello".toUpperCase();
" Hello ".trim();
" Hello ".trimStart();
" Hello ".trimEnd();
